Next.js - 環境構築
wada-mitsuki/next-app-template pull request #1
Opened 2024-01-23 04:55 UTC by wada-mitsuki

・`main`ブランチは`npx create-next-app@latest [PJ名] --ts` コマンド実行後にpushしたものになります。
・`develop`ブランチでは、以下の設定を行いました。

> ・prettire
> ・tailwindCSS
> ・eslint
> ・antd
> ・husky

・現在のローカル起動時画面は、Next.jsの初期画面が表示されます。
<img width="400" alt="スクリーンショット 2024-01-23 13 54 05" src="https://github.com/wada-mitsuki/next-app-template/assets/155605746/63cd739a-83f3-4601-b89a-4daaf013f4fc">

レビュー中に手順書を整理、まとめていますので、
他優先タスクがありましたらよろしくお願いいたします

2024-01-23 06:43 UTC, kamakura-hideki requested changes
@wada-mitsuki 

ローカルで save時に lint fix が効きませんでした 👀  
確認お願いします！
( yarn lint:fix は動作します)

コミット時の husky によるチェックは動作しています。

↓コミット時のエラー
```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
yarn run v1.22.19
$ /Users/note063/review/next-app-template/node_modules/.bin/lint-staged --config .lintstagedrc.js
[STARTED] Preparing lint-staged...
[COMPLETED] Preparing lint-staged...
[STARTED] Running tasks for staged files...
[STARTED] .lintstagedrc.js — 1 file
[STARTED] **/*.{ts,tsx,js,jsx} — 1 file
[STARTED] eslint --max-warnings=0 /Users/note063/review/next-app-template/src/pages/demo.tsx
[FAILED] eslint --max-warnings=0 /Users/note063/review/next-app-template/src/pages/demo.tsx [FAILED]
[FAILED] eslint --max-warnings=0 /Users/note063/review/next-app-template/src/pages/demo.tsx [FAILED]
[COMPLETED] Running tasks for staged files...
[STARTED] Applying modifications from tasks...
[SKIPPED] Skipped because of errors from tasks.
[STARTED] Reverting to original state because of errors...
[COMPLETED] Reverting to original state because of errors...
[STARTED] Cleaning up temporary files...
[COMPLETED] Cleaning up temporary files...

✖ eslint --max-warnings=0 /Users/note063/review/next-app-template/src/pages/demo.tsx:

/Users/note063/review/next-app-template/src/pages/demo.tsx
  11:5  error  Expected object keys to be in ascending order. 'age' should be before 'name'  sort-keys-fix/sort-keys-fix

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
husky - pre-commit hook exited with code 1 (error)
```

2024-01-23 07:41 UTC, maemura-katsuki commented
@wada-mitsuki  cc @kamakura-hideki 

> ローカルで save時に lint fix が効きませんでした 👀

一応、元々のプロジェクト自体で「save時に lint fix」は設定してませんでした！
せっかくなのでやってみてください 🙇

2024-01-23 07:41 UTC, wada-mitsuki commented
> @wada-mitsuki
> 
> ローカルで save時に lint fix が効きませんでした 👀 確認お願いします！ ( yarn lint:fix は動作します)

@kamakura-hideki 
setting.json - editor.formatOnSave(Prettierでの成形)をfalseにして
setting.json - source.fixAll.eslintを優先するようにしてみましたが、いかがでしょうか？ 👀 
ご確認お願いいたします🙇

自分の環境だと保存時に自動で成形・修正されることは確認しました。
（ちなみに前回の設定でも自動で成形されています 🤔 ）

以下のコミットで修正しました！
83a09aeb5f2992c03e094bdacb165606ca91621a

2024-01-23 07:42 UTC, maemura-katsuki commented on .eslintignore
> +index.tsx
ごめん、 `index.tsx` じゃなくて、 `index.ts` を除外してほしかったっす 🙏

そこ以外は特にありませんでした！

2024-01-23 07:45 UTC, wada-mitsuki commented on .eslintignore
> +index.tsx
あ。。。修正しました！！
（ndex.tsx じゃなくて、 index.tsを除外する理由調べてきます〜）

以下のコミットで修正しました！
d54fc13c0b5f23c82b7dc2709e428412aa5bad5a

2024-01-23 08:04 UTC, kamakura-hideki approved these changes
@wada-mitsuki 
ありがとうございます！確認しました！

2024-01-23 10:21 UTC, merged

2024-01-24 06:07 UTC, wada-mitsuki commented
@wada-mitsuki 
test